'use client'

import { useState } from 'react'

type TermProps = { children: React.ReactNode; name: string; definition: string }
function Term({ children, name, definition }: TermProps) {
  return <span className="term" tabIndex={0}>{children}<span className="term-popover"><strong>{name}</strong><span>{definition}</span></span></span>
}

const stages = ['Prepare data', 'Find features', 'Register scenes', 'Review quality']
const metrics = [['4,682', 'Reliable matches'], ['0.26 px', 'Registration error'], ['94.5%', 'Scene coverage']]

export default function LunarX() {
  const [section, setSection] = useState('overview')
  const [source, setSource] = useState('ch2_tmc_crater_scene_src.png')
  const [reference, setReference] = useState('ch2_tmc_crater_scene_ref.png')
  const [method, setMethod] = useState('LoFTR')
  const [running, setRunning] = useState(false)
  const [complete, setComplete] = useState(false)
  function runAlignment() { setRunning(true); setComplete(false); window.setTimeout(() => { setRunning(false); setComplete(true) }, 1200) }

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="isro-mark">ISRO</div><div><div className="brand-name">LUNAR<span>X</span></div><div className="brand-sub">Chandrayaan-2 image alignment</div></div></div><nav className="nav" aria-label="Main navigation">{['overview', 'alignment', 'glossary'].map(item => <button key={item} className={section === item ? 'active' : ''} onClick={() => setSection(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav><div className="status"><i /> Mission workspace <span className="status-divider" /> <span className="mono">SIH 26166</span></div></header>

    {section === 'overview' && <>
      <section className="hero page-width"><div className="hero-copy"><p className="eyebrow">ISRO · SPACE TECHNOLOGY</p><h1>Make every lunar image<br /><em>line up.</em></h1><p className="lede">LunarX aligns overlapping images from Chandrayaan-2 instruments so scientists can compare the Moon’s surface with confidence.</p><div className="hero-actions"><button className="primary" onClick={() => setSection('alignment')}>Start an alignment <span>→</span></button><button className="text-button" onClick={() => setSection('glossary')}>How it works <span>↗</span></button></div></div><div className="hero-visual"><div className="orbit-line" /><div className="moon"><div className="crater c1" /><div className="crater c2" /><div className="crater c3" /><div className="crater c4" /></div><div className="visual-label"><span className="pulse" /> Chandrayaan-2 · lunar surface</div></div></section>
      <section className="metrics page-width"><div className="metric-intro"><span className="section-number">01</span><p>Built for the evidence<br />behind the image.</p></div>{metrics.map(([value, label]) => <div className="metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
      <section className="story page-width"><div className="story-heading"><p className="eyebrow">THE MISSION</p><h2>From two images<br />to one clear view.</h2></div><div className="story-body"><p>Orbital images rarely arrive perfectly aligned. Small differences in camera angle, lighting, and spacecraft motion can hide the details that matter.</p><p>LunarX uses transparent, measurable steps to bring them together. No black box, no invented data—just a traceable result built on real mission imagery.</p><button className="text-button" onClick={() => setSection('alignment')}>Explore the workspace <span>→</span></button></div></section>
      <section className="feature-grid page-width"><article className="feature-card large"><div><span className="card-kicker">01 / COMPARE</span><h3>See the surface<br />as it was captured.</h3><p>Switch between the source image, reference image, and the registered result. Every view keeps the science in focus.</p></div><img src="/images/ch2_tmc_crater_scene_src_to_ch2_tmc_crater_scene_ref_loftr_registered.png" alt="Registered Chandrayaan-2 crater scene" /></article><article className="feature-card"><span className="card-kicker">02 / EXPLAIN</span><h3>Complex terms,<br />clear meaning.</h3><p>Hover over <Term name="LoFTR" definition="A deep-learning method that finds matching points between two images, even when they look different.">LoFTR</Term> or <Term name="SIFT" definition="A classic computer-vision method that identifies distinctive details and matches them between images.">SIFT</Term> to understand what is happening.</p><button className="outline" onClick={() => setSection('glossary')}>Open glossary</button></article></section>
    </>}

    {section === 'alignment' && <section className="workspace page-width"><div className="workspace-head"><div><p className="eyebrow">ALIGNMENT WORKSPACE</p><h1>Register two lunar scenes.</h1><p className="lede small">Choose your images and method. LunarX will create a measurable, reviewable alignment.</p></div><div className="run-status"><i className={complete ? 'done' : ''} /> {complete ? 'Alignment complete' : 'Ready to run'}</div></div><div className="stagebar">{stages.map((stage, i) => <div className={complete || i === 0 ? 'stage current' : 'stage'} key={stage}><b>0{i + 1}</b><span>{stage}</span></div>)}</div><div className="workspace-grid"><div className="controls panel"><div className="panel-title"><span>01</span><h2>Scene inputs</h2></div><label>Source scene<select value={source} onChange={e => setSource(e.target.value)}><option value="ch2_tmc_crater_scene_src.png">TMC-2 · Orbit 2019</option><option value="Pair_Crater_Region_Alpha_SRC.png">Crater Region Alpha</option></select></label><label>Reference scene<select value={reference} onChange={e => setReference(e.target.value)}><option value="ch2_tmc_crater_scene_ref.png">TMC-2 · Reference</option><option value="Pair_Crater_Region_Alpha_REF.png">Crater Region Alpha · Ref</option></select></label><div className="field-note"><span>✓</span> Verified Chandrayaan-2 mission product</div><div className="panel-title method-title"><span>02</span><h2>Alignment method</h2></div><div className="method-options">{['LoFTR', 'SIFT', 'SuperPoint'].map(item => <button className={method === item ? 'selected' : ''} key={item} onClick={() => setMethod(item)}><span className="radio" />{item}{item === 'LoFTR' && <small>recommended</small>}</button>)}</div><button className="primary run" onClick={runAlignment} disabled={running}>{running ? 'Aligning scenes…' : complete ? 'Run again' : 'Run alignment'} <span>→</span></button></div><div className="preview panel"><div className="preview-head"><div><span className="card-kicker">LIVE PREVIEW</span><h2>{complete ? 'Registered result' : 'Reference scene'}</h2></div><span className="mono image-code">TMC-2 / 5 m px</span></div><div className="image-stage"><img src={`/images/${complete ? 'ch2_tmc_crater_scene_src_to_ch2_tmc_crater_scene_ref_loftr_registered.png' : reference}`} alt="Lunar surface preview" /></div><div className="preview-caption"><span><i className="green-dot" /> {complete ? 'Alignment verified' : 'Awaiting alignment'}</span><span className="mono">{method} · {complete ? '0.26 px RMSE' : 'not run'}</span></div></div></div></section>}

    {section === 'glossary' && <section className="glossary page-width"><div className="glossary-intro"><p className="eyebrow">PLAIN-LANGUAGE GUIDE</p><h1>Space science,<br /><em>without the jargon.</em></h1><p className="lede small">LunarX is designed so that anyone can follow the evidence—from a student to a mission reviewer.</p></div><div className="terms-list">{[['PDS4', 'Planetary Data System 4', 'A standard format used to package and describe space-mission data. It keeps the image, its measurements, and its origin together.'], ['LoFTR', 'Local Feature TRansformer', 'A learned matching method. It looks at the relationship between entire image regions to find corresponding points, even in difficult lighting.'], ['SIFT', 'Scale-Invariant Feature Transform', 'A well-established computer-vision technique that finds distinctive details—such as crater edges—and matches them across images.'], ['Sub-pixel refinement', 'Fine-tuning below one pixel', 'A final precision step that adjusts a match by a fraction of a pixel, improving the accuracy of the registered image.'], ['RMSE', 'Root Mean Square Error', 'A measure of how far matched points are from where they should be. Lower is better; LunarX reports it in pixels.']].map(([term, full, desc]) => <article className="term-row" key={term}><div className="term-code">{term}</div><div><h2>{full}</h2><p>{desc}</p></div><span className="term-arrow">↗</span></article>)}</div></section>}
    <footer className="footer page-width"><span>Designed for SIH 26166 · ISRO</span><span className="mono">LUNARX / 2026</span></footer>
  </main>
}
