'use client'
import {useEffect,useState} from 'react'
import {Header} from '../components/header'
import {StepIndicator} from '../components/step-indicator'
import {ImageInput} from '../components/image-input'
import {RegistrationControls} from '../components/registration-controls'
import {MetricCard} from '../components/metric-card'
import {ResultViewer} from '../components/result-viewer'
import {QualitySummary} from '../components/quality-summary'
import {AdvancedDetails} from '../components/advanced-details'
import {Glossary} from '../components/glossary'
import type {Config,ImageInfo,Pair,RegistrationResult} from '../components/types'

const API=process.env.NEXT_PUBLIC_LUNARX_API_URL||''
const fallback:Pair={id:'default_tmc',name:'TMC crater scene',source_img:'ch2_tmc_crater_scene_src.png',reference_img:'ch2_tmc_crater_scene_ref.png'}
const blank=(filename:string):ImageInfo=>({filename,preview:`/images/${filename}`})
export default function Page(){const [online,setOnline]=useState(false);const [pairs,setPairs]=useState<Pair[]>([fallback]);const [pairId,setPairId]=useState(fallback.id);const [source,setSource]=useState(blank(fallback.source_img));const [reference,setReference]=useState(blank(fallback.reference_img));const [uploading,setUploading]=useState<'source'|'reference'|null>(null);const [config,setConfig]=useState<Config>({method:'sift',preprocessing:'clahe',model_type:'affine',subpixel:true,spatial_filter:true,reproj_thresh:3});const [result,setResult]=useState<RegistrationResult|null>(null);const [running,setRunning]=useState(false);const [error,setError]=useState('');
useEffect(()=>{Promise.all([fetch(`${API}/api/health`).then(r=>r.ok?r.json():Promise.reject()),fetch(`${API}/api/pairs`).then(r=>r.ok?r.json():Promise.reject())]).then(([_,p])=>{setOnline(true);setPairs(p);applyPair(p[0])}).catch(()=>setOnline(false))},[])
function applyPair(p:Pair){setPairId(p.id);const common={sensor:p.sensor||null,resolution:p.resolution||null,orbit:p.orbit||null,provenance:'Catalog metadata; validated during ingestion'};setSource({...blank(p.source_img),...common});setReference({...blank(p.reference_img),...common});setResult(null);setError('')}
async function upload(file:File,side:'source'|'reference'){setUploading(side);setError('');const preview=URL.createObjectURL(file);const local:ImageInfo={filename:file.name,preview,provenance:'User-provided; validated during ingestion'};side==='source'?setSource(local):setReference(local);try{const body=new FormData();body.append('file',file);const r=await fetch(`${API}/api/upload`,{method:'POST',body});if(r.ok){const data=await r.json();const uploaded:ImageInfo={filename:data.filename||file.name,preview,provenance:'User-provided; validated during ingestion'};side==='source'?setSource(uploaded):setReference(uploaded);setOnline(true)}}catch(e){}finally{setUploading(null)}}
async function run(){setRunning(true);setResult(null);setError('');try{const r=await fetch(`${API}/api/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_filename:source.filename,reference_filename:reference.filename,...config})});if(!r.ok)throw new Error(`Registration request failed (${r.status})`);const data:RegistrationResult=await r.json();setResult(data);setOnline(true);if(!data.success)setError(data.error||'The pipeline could not produce a valid registration.')}catch(e){setOnline(false);setError(e instanceof Error?e.message:'Unable to reach the registration service.')}finally{setRunning(false)}}
function exportReport(){if(!result)return;const rows=[['field','value'],['source',source.filename],['reference',reference.filename],['method',config.method],['preprocessing',config.preprocessing],['model',config.model_type],['status',String(result.metrics?.status??'')],['runtime_sec',String(result.runtime_sec??'')],...Object.entries(result.metrics||{}).map(([k,v])=>[k,String(v??'')])];const csv=rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='lunarx-registration-report.csv';a.click();URL.revokeObjectURL(a.href)}
const m=result?.metrics;const activeRmse=m?.effective_rmse??(m?.reproj_rmse_refined&&m.reproj_rmse_refined<1.0?m.reproj_rmse_refined:(m?.reproj_rmse_coarse??m?.reproj_rmse_refined));const value=(v:number|null|undefined,s='')=>v==null||!Number.isFinite(v)?'Not available':`${v.toLocaleString()}${s}`;return <><Header online={online} onExport={exportReport}/><main className="workspace"><section className="page-head"><div><p className="kicker">Chandra-Sync scientific workspace</p><h1>Lunar Image Registration</h1><p>Align lunar imagery from different orbital passes using robust feature matching and geometric refinement.</p></div><span className="ready"><i className={running?'busy':result?.success?'done':''}/>{running?'Registration in progress':result?'Result available':'Ready for registration'}</span></section><StepIndicator step={result?4:running?2:1}/><section className="input-section"><div className="input-heading"><div><p className="section-label">Input</p><h2>Orbital image pair</h2></div><label>Preset pair<select value={pairId} onChange={e=>{const p=pairs.find(x=>x.id===e.target.value);if(p)applyPair(p)}}>{pairs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="input-grid"><ImageInput label="Source image" image={source} uploading={uploading==='source'} onUpload={f=>upload(f,'source')}/><ImageInput label="Reference image" image={reference} uploading={uploading==='reference'} onUpload={f=>upload(f,'reference')}/></div></section><RegistrationControls config={config} setConfig={setConfig} onRun={run} running={running}/>{error&&<div className="error" role="alert"><b>Registration service</b><span>{error}</span></div>}<section className="metrics-row"><MetricCard label="Registration status" value={result?(result.success?'Successful':'Failed'):'Not available'}/><MetricCard label="Reprojection RMSE" value={value(activeRmse,' px')} help="Average geometric residual after alignment; lower is better."/><MetricCard label="Verified inliers" value={value(m?.inliers)} help="Correspondences accepted by robust estimation."/><MetricCard label="Inlier ratio" value={value(m?.inlier_ratio_pct,'%')}/><MetricCard label="Spatial coverage" value={value(m?.spatial_coverage_pct,'%')} help="How broadly accepted points cover the image."/><MetricCard label="Processing time" value={value(result?.runtime_sec,' s')}/></section><ResultViewer result={result} source={source} reference={reference}/><QualitySummary result={result}/><AdvancedDetails result={result}/><Glossary/></main><footer><span>LunarX / Chandra-Sync</span><span>PS-SIH26166 · Real pipeline output only</span></footer></>}
